### PR TITLE
Adding code for automatically updating the Google Calendar

### PR DESCRIPTION
**Pull request by gmriggs**
Hey @ItsASine!

Here is code for automatically updating the Google Calendar from the in-game motd

It is written in JS, and can be run anywhere via Node.js (v4+ required for the official Google API)

Here's a quick rundown of how it works:

- Event.js - this is the data format for the event locations and dates / time ranges
- MOTD.js - This is a Node.js compatible version of the GW2 API reader for the guild MOTD.
- Parser.js - This reads the messages and looks for event locations, and dates/times for the events. It has been tested with the last 25 MOTD updates for the guild.
- Calendar.js - This is the main executable that should be called with Node. It gets the MOTD, parses it for events, and posts any updates to the Google Calendar

The Google Calendar API is made accessible via setting up a service account:

https://developers.google.com/google-apps/calendar/quickstart/nodejs

Only Step 1 of these instructions are needed for setup. It will produce a client_secret.json file, which should be saved to the calendar/config folder

On the first run of Calendar.js, an authentication token will be requested and saved locally

It was developed using just a test calendar, but can work with any calendar if you or Moon would like to authorize a service account for the official SAND calendar

Since this is something that can be run from anywhere, and doesn't necessarily need to reside in the main repository for the site, this pull request is mostly for code review and discussion of the design. I would be able to set this script to run on a server every ~1 hour or so.

Let me know when you have some time to check it out :)

### CODE REVIEW

**Comment by gmriggs** [comment]
Hey @ItsASine,

When you get a chance, can you enable a service account for the SAND calendar, and also provision my gmriggs@gmail.com account to manually make calendar updates?

**Comment by ItsASine** [comment]
@gmriggs I added your Gmail to the calendar and will set up the service account tonight (It's difficult trying to navigate the menu trees when remoted in to a computer via an iPad).

I'm going to start taking a look around your code ASAP though :) Thanks for the help!

**Review by ItsASine — APPROVED** [review]

**Comment by ItsASine** [comment]
@gmriggs 

This was merged as 7895e01a1fe2e54099a2e3cc75f03bf60bbfa8f2 for pumpkins and 7895e01a1fe2e54099a2e3cc75f03bf60bbfa8f2 for the calendar. 

Let me know if you need anything else!

**Comment by gmriggs** [comment]
Thank you so much @ItsASine!!

I'm glad to help keep the calendar updated with all the latest guild events. Hopefully this script will help automate everything!

Also regarding the pumpkin updates: I was unaware that additional commits to my branch of the SAND repo would be automatically included in this pull request. Everything should still be fine for the main website, but I will keep the separate features in their own branches in the future, to avoid any confusion, and to keep everything clean and organized.

Thanks again, and if there are any other features on the site that I could tackle, I would be very happy to help out in any way I can!

**Comment by ItsASine** [comment]
@gmriggs 

I sent you an invite to join the drytopsand github org so you can make your own modifications as you need without me (if you want, or we can make this seem somewhat legit and have peer code reviews).

Also, you/me can revert that pumpkin commit if you want. Yay squashing things into easy to find packages!

Branching would make things super useful, though at least with pages that aren't linked to elsewhere it's easy to point Moon to it without someone casually stumbling upon it.

Speaking of @MuirelltheMoon , I'll ping her so she knows I gave you more permissions. Though now you get to get all the Twitter DMs for site updates 😉

**Comment by gmriggs** [comment]
Awesome, I will be sure to send out requests for code reviews for anything of significance!

Yeah I can revert that pumpkin commit, and re-check it in separately from the Google Calendar stuff

Thanks again for the wonderful guild website, I hope to help keep it updated and make everything a little bit easier for everyone! :)

**Pull request closed without merging**
